### ISSUE TITLE
Projects only doing codescan but have no whitelist entry throw NPE

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#14]
Current situation: When a project is defined in SecHub without having a whitelist entry we got a NPE . Sometimes we got projects doing only a code scan, so even a empty list must be valid.

**Comment by de-jcup** [comment]
Current workaround is to always add a dummy entry - e.g. "http://example.com" as whitelist entry

**Comment by de-jcup** [comment]
Hmm.. tried out old version (0.10.3) and there tests do not fail but there was an error

After trying out to create a project I found a way to reproduce the problem:

1. create some testdata (e.g. start an integration test)
2. now create a new project by DeveloperAdmin UI:
  - name "testproject" 
  - description "xxx"
  -  user: $existingFromTest
  - whitelist: at first dialog just press OK on next dialog do the cancel (exact this way)

3. assign this user to the project.
4. execute a normal scan e.g. by sechub command client

**Comment by de-jcup** [comment]
There is another problem: When adding something not being valid (e.g. the empty entry in former first white list dialog) we cannot delete the project any longer:

```
org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "C04_ADM_PROJECTWHITELIST_PROJECT_ID: PUBLIC.ADM_PROJECT_WHITELIST_URI FOREIGN KEY(PROJECT_PROJECT_ID) REFERENCES PUBLIC.ADM_PROJECT(PROJECT_ID) ('testproject')"; SQL statement:
delete from adm_project where project_id=? and version=? [23503-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
...
	at com.daimler.sechub.domain.administration.project.ProjectDeleteService.deletProject(ProjectDeleteService.java:42) ~[main/:na]
	at com.daimler.sechub.domain.administration.project.ProjectDeleteService$$FastClassBySpringCGLIB$$b95f38d3.invoke(<generated>) ~[main/:na]
...
```
