### ISSUE TITLE
Fix spring security context problem on event bus execution

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#216]
### Situation
ProductResultService contained a  `@RolesAllowed` annotation with super admin role constraint

A rest controller which was also secured to super admin role and did call some services
which leads to execution of product result service via Event Bus.

### Problem
The Spring security context is not accepted :
Here an output from integration test UC_ADMIN_RESTARTS_JOB_HARD__simulate_accidently_job_restarted_where_already_done

log:
```
...
2020-04-23 20:02:55.903 DEBUG 14188 --- [xecutor_thread3] c.d.s.domain.scan.ScanMessageHandler     : received synchron domain request: DomainMessage [id=REQUEST_PURGE_JOB_RESULTS, parameters={environment.base.url=https://localhost:8443, sechub.uuid=4b9eaff1-a118-4f7d-b44f-1c053969cf5e}]
2020-04-23 20:02:55.905 ERROR 14188 --- [xecutor_thread3] c.d.s.domain.scan.ScanMessageHandler     : Was not able to purge results for job {}

org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:223)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.daimler.sechub.domain.scan.product.ProductResultService$$EnhancerBySpringCGLIB$$d1ad7bdd.deleteAllResultsForJob(<generated>)
	at com.daimler.sechub.domain.scan.ScanMessageHandler.handleJobRestartHardRequested(ScanMessageHandler.java:106)
	at com.daimler.sechub.domain.scan.ScanMessageHandler.receiveSynchronMessage(ScanMessageHandler.java:94)
	at com.daimler.sechub.sharedkernel.messaging.DomainMessageService.sendSynchron(DomainMessageService.java:147)
	at com.daimler.sechub.sharedkernel.messaging.DomainMessageService$$FastClassBySpringCGLIB$$c7de0c21.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.daimler.sechub.sharedkernel.messaging.DomainMessageService$$EnhancerBySpringCGLIB$$83df6b4.sendSynchron(<generated>)
	at com.daimler.sechub.domain.schedule.SchedulerRestartJobService.sendPurgeJobResultsRequest(SchedulerRestartJobService.java:202)
	at com.daimler.sechub.domain.schedule.SchedulerRestartJobService.restartJob(SchedulerRestartJobService.java:120)
	at com.daimler.sechub.domain.schedule.SchedulerRestartJobService.restartJobHard(SchedulerRestartJobService.java:84)
	at com.daimler.sechub.domain.schedule.ScheduleMessageHandler.handleJobRestartHardRequested(ScheduleMessageHandler.java:119)
	at com.daimler.sechub.domain.schedule.ScheduleMessageHandler.receiveAsyncMessage(ScheduleMessageHandler.java:99)
	at com.daimler.sechub.sharedkernel.messaging.DomainMessageService$AsynchronMessageHandlerTaskAdapter.run(DomainMessageService.java:199)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-04-23 20:02:55.906 ERROR 14188 --- [xecutor_thread3] c.d.s.s.messaging.DomainMessageService   : Was not able to run request:DomainMessage [id=REQUEST_JOB_RESTART_HARD, parameters={environment.base.url=https://localhost:8443, job.restart.data={"jobUUID":"4b9eaff1-a118-4f7d-b44f-1c053969cf5e"}}] with handler com.daimler.sechub.domain.schedule.ScheduleMessageHandler@73852720
...
```

### Workaround
Temporarily commented out the annotation inside service  - but solution necessary!

### Solution
Move security context into call
e.g. something like:

 ```
 try {
            SecurityContext ctx = SecurityContextHolder.createEmptyContext();
            SecurityContextHolder.setContext(ctx);
            ctx.setAuthentication(event.getAuthentication());

            //Do what ever you want to do

        } finally {
            SecurityContextHolder.clearContext();
        }
 ```

**Comment by de-jcup** [comment]
Informative:

https://www.javacodegeeks.com/2018/02/securitycontext-securitycontextholder-spring-security.html

**Comment by de-jcup** [comment]
https://www.baeldung.com/spring-security-async-principal-propagation describes usage of @Async and SecurityContextHolder Strategy seems to show the solution

**Comment by de-jcup** [comment]
Candidates for adding roles allowed annotation after fixing this problem:
- SchedulerRestartJobService

**Comment by de-jcup** [comment]
With #192 the  problem with task executors become more serious - in the event message the security context as lost and the checks were no longer possible because of missing authentication.

After some reasearch I found 
https://github.com/spring-projects/spring-security/issues/6856#issuecomment-518787966
which seems to contain the the solution: We will change `SecHubServerThreadConfiguration.java` by adding a task decorator and use the `DelegatingSecurityContextRunnable` so the runnables executed by the task executor will inherit the security context from the caller.

```java 
@Configuration
public class SecHubServerThreadConfiguration {

	@Bean
	@Primary
	public TaskExecutor threadPoolTaskExecutor() {
		// .. as before
		executor.setTaskDecorator(runnable -> new DelegatingSecurityContextRunnable(runnable));
                // .. as before
		return executor;
	}

}
```
We will apply the solution for `PDSThreadConfiguration.java` as well

Those changes will be done together with #192 in same feature branch
