### ISSUE TITLE
Cannot delete sechub job because of jackson invalid type id

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#499]
When we cancel an older job - being marked as still running -  we got an exception

Interesting part of trace:

---
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: 
Missing type id when trying to resolve subtype of 
[map type; class java.util.HashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.Object]]: missing type id property '@class' at [Source: (ByteArrayInputStream); line: 1, column: 2] at
 com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43) at
...
org.springframework.batch.core.repository.dao.**JdbcExecutionContextDao**$ExecutionContextRowMapper.mapRow(JdbcExecutionContextDao.java:325) ... 43 common frames omitted

---

Full stacktrace:

 ```
	java.lang.IllegalArgumentException:
Unable to deserialize the execution context at
 org.springframework.batch.core.repository.dao.JdbcExecutionContextDao$ExecutionContextRowMapper.mapRow(JdbcExecutionContextDao.java:328) at
 org.springframework.batch.core.repository.dao.JdbcExecutionContextDao$ExecutionContextRowMapper.mapRow(JdbcExecutionContextDao.java:312) at
 org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94) at
 org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61) at
 org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:723) at
 org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) at
 org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713) at
 org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744) at
 org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757) at
 org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:815) at
 org.springframework.batch.core.repository.dao.JdbcExecutionContextDao.getExecutionContext(JdbcExecutionContextDao.java:114) at
 org.springframework.batch.core.explore.support.SimpleJobExplorer.getJobExecutionDependencies(SimpleJobExplorer.java:232) at
 org.springframework.batch.core.explore.support.SimpleJobExplorer.findRunningJobExecutions(SimpleJobExplorer.java:116) at
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at
 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at
 java.base/java.lang.reflect.Method.invoke(Unknown Source) at
 org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) at
 org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) at
 org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at
 org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128) at
 org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at
 org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) at
 com.sun.proxy.$Proxy122.findRunningJobExecutions(Unknown Source) at
 com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService.stopAllRunningBatchJobsForSechubJobUUID(SchedulerCancelBatchJobService.java:60) at
 com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService.stopAllRunningBatchJobsForSechubJobUUID(SchedulerCancelBatchJobService.java:39) at
 com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService$$FastClassBySpringCGLIB$$1c3d2bc5.invoke(<generated>) at
 org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at
 org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) at
 org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at
 org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) at
 org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371) at
 org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134) at
 org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at
 org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) at
 org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) at
 com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService$$EnhancerBySpringCGLIB$$5e13b8f5.stopAllRunningBatchJobsForSechubJobUUID(<generated>) at
 com.daimler.sechub.domain.schedule.SchedulerCancelJobService.cancelJob(SchedulerCancelJobService.java:76) at
 com.daimler.sechub.domain.schedule.ScheduleMessageHandler.handleCancelJobRequested(ScheduleMessageHandler.java:125) at
 com.daimler.sechub.domain.schedule.ScheduleMessageHandler.receiveAsyncMessage(ScheduleMessageHandler.java:93) at
 com.daimler.sechub.sharedkernel.messaging.DomainMessageService$AsynchronMessageHandlerTaskAdapter.run(DomainMessageService.java:197) at
 java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at
 java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at
 java.base/java.lang.Thread.run(Unknown Source) Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [map type; class java.util.HashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.Object]]: missing type id property '@class' at
 [Source: (ByteArrayInputStream); line: 1, column: 2] at
 com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43) at
 com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1794) at
 com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1323) at
 com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:303) at
 com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:166) at
 com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:107) at
 com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserializeWithType(MapDeserializer.java:413) at
 com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68) at
 com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526) at
 com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3513) at
 org.springframework.batch.core.repository.dao.Jackson2ExecutionContextStringSerializer.deserialize(Jackson2ExecutionContextStringSerializer.java:133) at
 org.springframework.batch.core.repository.dao.Jackson2ExecutionContextStringSerializer.deserialize(Jackson2ExecutionContextStringSerializer.java:104) at
 org.springframework.batch.core.repository.dao.JdbcExecutionContextDao$ExecutionContextRowMapper.mapRow(JdbcExecutionContextDao.java:325) ... 43 common frames omitted
```

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
I think this is related to our last upgrade to newer spring boot version done in our last release, see 
https://github.com/spring-projects/spring-batch/issues/3732

**Comment by de-jcup** [comment]
We need to create a test where

- a sechub job is created, sechub job uuid is wellknown
- it is ensured sechub job is running 
- sechub job takes enough time to be interruptable by  `SchedulerCancelBatchJobService.stopAllRunningBatchJobsForSechubJobUUID(wellknownUUID)`

Points of interest:
- ScanExecutionTasklet
- BatchConfiguration

The problem stack is not 100% helpful. To check explicit content it should be valuable to create the test let it fail and then create a breakpoint to inspect the exact used classes/structure.
After the inspection object mapper should allow wanted content by mixins.

**Comment by de-jcup** [comment]
Hm... leads to another problem:

```
org.springframework.batch.core.launch.NoSuchJobException: No job configuration with the name [executeScan] was registered
	at org.springframework.batch.core.configuration.support.MapJobRegistry.getJob(MapJobRegistry.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy148.getJob(Unknown Source)
	at org.springframework.batch.core.launch.support.SimpleJobOperator.stop(SimpleJobOperator.java:388)
	at org.springframework.batch.core.launch.support.SimpleJobOperator$$FastClassBySpringCGLIB$$44ee6049.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.springframework.batch.core.launch.support.SimpleJobOperator$$EnhancerBySpringCGLIB$$33502772.stop(<generated>)
	at com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService.stop(SchedulerCancelBatchJobService.java:81)
	at com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService.stopAllRunningBatchJobsForSechubJobUUID(SchedulerCancelBatchJobService.java:67)
	at com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService.stopAllRunningBatchJobsForSechubJobUUID(SchedulerCancelBatchJobService.java:39)
	at com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService$$FastClassBySpringCGLIB$$1c3d2bc5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.daimler.sechub.domain.schedule.batch.SchedulerCancelBatchJobService$$EnhancerBySpringCGLIB$$8ea99766.stopAllRunningBatchJobsForSechubJobUUID(<generated>)
	at com.daimler.sechub.domain.schedule.SchedulerCancelJobService.cancelJob(SchedulerCancelJobService.java:76)
	at com.daimler.sechub.domain.schedule.ScheduleMessageHandler.handleCancelJobRequested(ScheduleMessageHandler.java:125)
	at com.daimler.sechub.domain.schedule.ScheduleMessageHandler.receiveAsyncMessage(ScheduleMessageHandler.java:93)
	at com.daimler.sechub.sharedkernel.messaging.DomainMessageService$AsynchronMessageHandlerTaskAdapter.run(DomainMessageService.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by de-jcup** [comment]
Looks similar to
https://stackoverflow.com/questions/64812386/spring-batch-exception-org-springframework-batch-core-launch-nosuchjobexception

The proposal is to add a `JobRegistryBeanPostProcessor` to the application context.

**Comment by de-jcup** [comment]
Now back to origin problem: 
- also mentioned in
https://stackoverflow.com/questions/62718203/spring-batch-4-2-4-unable-to-deserialize-the-execution-context but the proposal to replace the entries with "{}" is not the way to go, because every new batch job seems to setup the hash map info again.
- after looking in DB at the beginning we had just a "{}" inside the batch_job_execution_context table . But newer entries have all a 
  `{"@class":"java.util.HashMap"}`as short_context inside. Means an empty hash map is deserialized

**Comment by de-jcup** [comment]
## Analyse result
Unfortunetly we cannot write a simple integration test and reproduce the problem in integration test mode.

Reason: With newer spring boot batch because of CVE protection the framework does no longer support serialization parts which are not typed - and a simple `{}` is not typed for the framework. But the old spring batch implementation did wrote `{}` when no context was defined - pretty simple, reduces memory and clear. The new implementation does always insist on a @class meta information - no matter if there is nothing defined at all...

I think the protection about serialization vulnerabilities is very important - and the  implementation inside spring batch does protect here, but... `{}` should be recognized as null - or an empty list or what ever necessary to handle this kind of stuff. If this would be done we wouldn't need to make any changes here and it would have not made migration problems at SecHub or other OSS projects using spring batch framework.

## Test approach
Because it is not possible to reproduce this by just a simple integration test  (we would need to run different sechub server instances, with different versions and additionally a persistent database etc. ) without too much effort we will do following simple test approach:

### Demo application
We creata a s simple spring boot demo application with https://start.spring.io/ having spring.datasource.jpa and spring.batch as dependencies.

```java
package com.example.demo;

import java.util.Set;

import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.explore.JobExplorer;
import org.springframework.batch.core.launch.JobOperator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@EnableBatchProcessing
public class DemoApplication implements CommandLineRunner {
    
    
    private static final String JOB_NAME_EXECUTE_SCAN = "executeScan";
    
    @Autowired
    JobExplorer explorer;
    
    @Autowired
    JobOperator operator;

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	
	@Override
	public void run(String... args) throws Exception {
	    fetchData();
	}
	
	private void fetchData() {
	    Set<JobExecution> found = explorer.findRunningJobExecutions(JOB_NAME_EXECUTE_SCAN);
	    System.out.println("found job executions:"+found.size());
	    for (JobExecution exec :  found) {
	        System.out.println("- job id:"+exec.getId());
	    }
	}
	
}

```

### Preparations
#### DEV environment
- Inside a running instance (e.g. DEV environment) we simulate old values and test behaviour.
- follow prepare data

#### Local environment with h2 tcp enabled
- If no DEV environment is available where jobs can be fetched you can also start an integration test server with h2 tcp enabled:

- start sechub integration test server with h2 tcp enabled: 
```
-Dh2.tcp.enabled=true
-Dspring.profiles.active=dev,mocked_products,h2,integrationtest
-Dsechub.storage.sharedvolume.upload.dir=temp
```
- start an integration test which does trigger a sechub job
- after this change directly in database entry for execution.short_context from `{"@class":"java.util.HashMap"}` to `{}`
- follow prepare data
- 
#### Prepare data
- before preparation, start the demo application there shall be no errors
- after this execute:
  `select * from batch_job_execution_context c limit 1` and remember the job_execution_id - we use `3` in example description
- now mark this as "running"
`update batch_job_execution set status='STARTED', end_time=null, exit_code=null where job_execution_id=3`
- now start demo application again - it will show at least our marked entry.
- now make it problematic by executing 
  `update batch_job_execution_context set short_context='{}' where job_execution_id=3`
- now start demo application again - it will fail with same exception as mentioned before at top of this issue
- now we "heal" the problem by doing a 
`update batch_job_execution_context set short_context='{"@class":"java.util.HashMap"}' where job_execution_id=3`
- now start demo application again - it will show at least our marked entry, no exception!

**Comment by de-jcup** [comment]
So we should at least provide a flyway migration script where all batch_job_excecution_context table rows will be updated from `{}` to '{"@class":"java.util.HashMap"}' where the status is still be `STARTED`

**Comment by de-jcup** [comment]
With last 9b9b314 we also added SQL snippet to change and test step execution context format problems, becausemany old entries contain:
`{"batch.taskletType":"com.daimler.sechub.domain.schedule.batch.ScanExecutionTasklet","batch.stepType":"org.springframework.batch.core.step.tasklet.TaskletStep"}`

The SQL snippet changes those to
`{"@class":"java.util.HashMap","batch.taskletType":"com.daimler.sechub.domain.schedule.batch.ScanExecutionTasklet","batch.stepType":"org.springframework.batch.core.step.tasklet.TaskletStep"}`
