### ISSUE TITLE
PDS: Unable to unzip folders

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#631]
## Issue

The PDS is unable to unzip folders. Unzipping a folder causes an exception:

```
java.io.FileNotFoundException: /home/developer/pds/workspace/7e8df633-83d6-4042-bc75-5435e83b7dd1/upload/unzipped/sourcecode/abc/hardcoded_password.go (Not a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.daimler.sechub.pds.util.PDSFileUnzipSupport.unzipArchive(PDSFileUnzipSupport.java:37)
	at com.daimler.sechub.pds.job.PDSWorkspaceService.unzipUploads(PDSWorkspaceService.java:94)
	at com.daimler.sechub.pds.job.PDSWorkspaceService.unzipUploadsWhenConfigured(PDSWorkspaceService.java:74)
	at com.daimler.sechub.pds.execution.PDSExecutionCallable.call(PDSExecutionCallable.java:75)
	at com.daimler.sechub.pds.execution.PDSExecutionCallable.call(PDSExecutionCallable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Example ZIP: [abc.zip](https://github.com/Daimler/sechub/files/6503280/abc.zip)

## Wanted

The PDS can unzip complex and nested folders structures without throwing an exception.

**Comment by Jeeppler** [comment]
A single zipped file works, with no issues: [single_file.zip](https://github.com/Daimler/sechub/files/6503312/single_file.zip)

**Comment by Jeeppler** [comment]
The code examples in `abc.zip` and `single_file.zip` are from:

- https://securego.io/docs/rules/g101.html
- https://securego.io/docs/rules/g201-g202.html
