### ISSUE TITLE
Flaky test - PDSJSONConverterException happens sometimes

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#730]
## Situation
`DirectPDSAPIMonitoringStateScenario6IntTest[combined-sechub-testreport.zip](https://github.com/Daimler/sechub/files/6868525/combined-sechub-testreport.zip)java` the method `pds_admin_can_fetch_execution_state`
does sometimes fails on github actions  with a JSON conversion problem. 

### GitHub actions
- Problem was at least 2 times
- Restart of job did resolve the problem
- Currently not known to happen in "real live"

### Jenkins
- never happend (as far as I know)

#### Gradle
- never happend (as far as I know)
#### IDE (eclipse)
- never happend (as far as I know)

So we got a flaky test or a flaky problem

## Wanted
The problem/reason must be found and fixed We do not want flaky tests and also that the problem not happens in a real scenario.

## Additional Information
All files from failed build are available at: [combined-sechub-testreport.zip](https://github.com/Daimler/sechub/files/6868539/combined-sechub-testreport.zip)

Here the relevant part on the PDS server log (which is the reason why the test did not receive the expected JSON data):
```
2021-07-23 11:08:01.638 ERROR 9876 --- [0.1-8444-exec-9] c.d.s.pds.monitoring.PDSClusterMember    : cannot convert json to cluster member

com.daimler.sechub.pds.PDSJSONConverterException: Was not able to convert JSON string to class com.daimler.sechub.pds.monitoring.PDSClusterMember object
	at com.daimler.sechub.pds.PDSJSONConverter.fromJSON(PDSJSONConverter.java:103)
	at com.daimler.sechub.pds.monitoring.PDSClusterMember.fromJSON(PDSClusterMember.java:98)
	at com.daimler.sechub.pds.monitoring.PDSMonitoringStatusService.addHeartBeatDataAsMember(PDSMonitoringStatusService.java:46)
	at com.daimler.sechub.pds.monitoring.PDSMonitoringStatusService.getMonitoringStatus(PDSMonitoringStatusService.java:38)
	at com.daimler.sechub.pds.monitoring.PDSAdminMonitoringRestController.getMonitoringStatus(PDSAdminMonitoringRestController.java:38)
	at com.daimler.sechub.pds.monitoring.PDSAdminMonitoringRestController$$FastClassBySpringCGLIB$$713cef8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at [combined-sechub-testreport.zip](https://github.com/Daimler/sechub/files/6868539/combined-sechub-testreport.zip)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
	at com.daimler.sechub.pds.PDSJSONConverter.fromJSON(PDSJSONConverter.java:100)
	... 102 common frames omitted

```

**Comment by de-jcup** [comment]
This is a duplicate of #804
