### ISSUE TITLE
PDS unzip problems

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#773]
## Situation
While testing PR #696 when starting a gosec scan and using latest sechub-cli client  and using sechub OSS root folder for source uploads, the PDS server cannot unzip the sources and the scan fails.

The scan was done via DAUI and which did trigger the scan via local built sechub client (develop branch).

The SecHub server was started local in IntegrationTestMode and a local postgres installation. Used shared volume storage.
The GoSec PDS server was start with 01-... script (single) and the PDS adapter was configured to NOT reuse SecHub storage.

```java
java.io.FileNotFoundException: /workspace/workspace/cf0526f5-de35-4937-93af-440f3b6fd24b/upload/unzipped/sourcecode/docs/latest/sechub-architecture.html (No such file or directory)
...
at com.daimler.sechub.pds.util.PDSFileUnzipSupport.copy(PDSFileUnzipSupport.java:84)
```
_(the full log can be found below)_

## Wanted
- We must inspect if the sechub client does accidently add filtered files to zip header but does not add them as content only
- identify the problem

## Solution
- Inspect problem on client side / zipped content
- Inspect reason for problem on copy
 

## Details
```
pds-gosec-ubuntu    | 2021-09-02 12:57:54.628  INFO 8 --- [0.0-8444-exec-5] c.d.sechub.pds.job.PDSCreateJobService   : Job cf0526f5-de35-4937-93af-440f3b6fd24b has been created
pds-gosec-ubuntu    | 2021-09-02 12:57:55.979  INFO 8 --- [0.0-8444-exec-6] c.d.s.pds.job.PDSFileUploadJobService    : Upload file sourcecode.zip for job cf0526f5-de35-4937-93af-440f3b6fd24b to storage
pds-gosec-ubuntu    | 2021-09-02 12:57:55.981  INFO 8 --- [0.0-8444-exec-6] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:cf0526f5-de35-4937-93af-440f3b6fd24b: storing sourcecode.zip in path pds/GOSEC_CLUSTER
pds-gosec-ubuntu    | 2021-09-02 12:57:55.988  INFO 8 --- [0.0-8444-exec-6] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:cf0526f5-de35-4937-93af-440f3b6fd24b: storing sourcecode.zip.checksum in path pds/GOSEC_CLUSTER
pds-gosec-ubuntu    | 2021-09-02 12:57:56.386  INFO 8 --- [0.0-8444-exec-7] c.d.s.pds.job.PDSJobTransactionService   : Mark job cf0526f5-de35-4937-93af-440f3b6fd24b as ready to start
pds-gosec-ubuntu    | 2021-09-02 12:57:56.772  INFO 8 --- [pool-2-thread-1] c.d.s.p.execution.PDSExecutionCallable   : Prepare execution of job cf0526f5-de35-4937-93af-440f3b6fd24b
pds-gosec-ubuntu    | 2021-09-02 12:57:56.796 ERROR 8 --- [pool-2-thread-1] c.d.s.p.execution.PDSExecutionCallable   : Execution of job uuid:cf0526f5-de35-4937-93af-440f3b6fd24b failed
pds-gosec-ubuntu    | 
pds-gosec-ubuntu    | java.io.FileNotFoundException: /workspace/workspace/cf0526f5-de35-4937-93af-440f3b6fd24b/upload/unzipped/sourcecode/docs/latest/sechub-architecture.html (No such file or directory)
pds-gosec-ubuntu    | 	at java.base/java.io.FileOutputStream.open0(Native Method)
pds-gosec-ubuntu    | 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
pds-gosec-ubuntu    | 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
pds-gosec-ubuntu    | 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
pds-gosec-ubuntu    | 	at com.daimler.sechub.pds.util.PDSFileUnzipSupport.copy(PDSFileUnzipSupport.java:84)
pds-gosec-ubuntu    | 	at com.daimler.sechub.pds.util.PDSFileUnzipSupport.unzipArchive(PDSFileUnzipSupport.java:66)
pds-gosec-ubuntu    | 	at com.daimler.sechub.pds.job.PDSWorkspaceService.unzipUploads(PDSWorkspaceService.java:186)
pds-gosec-ubuntu    | 	at com.daimler.sechub.pds.job.PDSWorkspaceService.unzipUploadsWhenConfigured(PDSWorkspaceService.java:165)
pds-gosec-ubuntu    | 	at com.daimler.sechub.pds.execution.PDSExecutionCallable.call(PDSExecutionCallable.java:78)
pds-gosec-ubuntu    | 	at com.daimler.sechub.pds.execution.PDSExecutionCallable.call(PDSExecutionCallable.java:34)
pds-gosec-ubuntu    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
pds-gosec-ubuntu    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
pds-gosec-ubuntu    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
pds-gosec-ubuntu    | 	at java.base/java.lang.Thread.run(Thread.java:829)
pds-gosec-ubuntu    | 
pds-gosec-ubuntu    | 2021-09-02 12:57:56.798  INFO 8 --- [pool-2-thread-1] c.d.sechub.pds.job.PDSWorkspaceService   : Removed workspace folder for job cf0526f5-de35-4937-93af-440f3b6fd24b
pds-gosec-ubuntu    | 2021-09-02 12:57:56.802  INFO 8 --- [pool-2-thread-1] c.d.s.s.s.spring.SharedVolumeJobStorage  : deleted all inside /shared_volumes/uploads/pds/GOSEC_CLUSTER/cf0526f5-de35-4937-93af-440f3b6fd24b
pds-gosec-ubuntu    | 2021-09-02 12:57:56.802  INFO 8 --- [pool-2-thread-1] c.d.sechub.pds.job.PDSWorkspaceService   : Removed storage for job cf0526f5-de35-4937-93af-440f3b6fd24b
pds-gosec-ubuntu    | 2021-09-02 12:57:56.802  INFO 8 --- [pool-2-thread-1] c.d.s.p.execution.PDSExecutionCallable   : Finished execution of job cf0526f5-de35-4937-93af-440f3b6fd24b with exitCode=0, failed=true
```

**Comment by de-jcup** [comment]
This is not a client problem - we tested and the created ZIP file was correct.

**Comment by de-jcup** [comment]
Maybe the problem is because of the different storages. 

SecHub: storage : shared volume on local macine
PDS gosec: storage: shared volume inside docker container

**Comment by Jeeppler** [comment]
The issue occurs in Kubernetes with object storage (s3) as well. Regardless of whether the storage is shared between SecHub or not (`pds.config.use.sechub.storage=false or true`).
