### ISSUE TITLE
Handle CLOB hibernate exception

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#81]
When using postgres as DB Hibernate has got a Probelm with @CLOB annotation
```
2019-11-13 19:18:53.361  INFO 7 --- [           main] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl.useContextualLobCreation(LobCreatorBuilderImpl.java:113) [hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
```

**Comment by de-jcup** [comment]
This is an hibernate issue:
https://hibernate.atlassian.net/browse/HHH-12368
and was fixed with `hibernate 5.4.0.CR1`

When we would jump to spring boot 2.2.0 this should be automatically fixed, because this version uses hibernate 5.4 as dependency (and no longer 5.3 as spring boot 2.1)
