### ISSUE TITLE
Fix bugs and test race-conditions for role owner change usecase

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#826]
## Situation
The integration test `ProjectAdministrationScenario3IntTest` does sometimes fail inside the method
`when_a_superadmin_assigns_another_owner_to_all_projects_the_previous_owner_loses_owner_role`:

```java
java.lang.AssertionError: No rest client exception - so user at least got a HTTP 20x what is wrong! Timeout reached:10221/10000 ms.
	at org.junit.Assert.fail(Assert.java:89)
	at com.daimler.sechub.integrationtest.api.TestAPI.expectHttpFailure(TestAPI.java:407)
	at com.daimler.sechub.integrationtest.api.AssertUser.hasNotOwnerRole(AssertUser.java:458)
	at ...
```
## Wanted
Test shall not be flaky.

## Solution 1 (outdated)
It seems to be a race condition - when events are not handled fast enough and at test check the user role is still "owner".

Instead of doing here a simple `TestAPI.waitMilliseconds(300)`, we we will  first try - and if it fails, wait some time and try again.
This shall be available inside `TestAPI` class and must be used inside the `AssertUser`/`AssertProject` classes

## Solution 2(new)
It is not a flaky test but a flaky implementation - eventhandling is done asynchronous. See next comment for details.

**Comment by de-jcup** [comment]
The problem still exists - this is an implementation problem and not a problem inside test!

```java
        sendOwnerChangedForProjectEvent(project, previousOwner, newOwner);
        
        sendRequestOwnerRoleRecalculation(newOwner);
        sendRequestOwnerRoleRecalculation(previousOwner);
```
we got race conditions here - the first sent event is sometimes not be done but the other both for recalculation could be already processed!

So sending the role recalculation must be triggered not here, but when the owner change has been done!

**Comment by de-jcup** [comment]
Inside the `ProjectAssignOwnerService` the wrong usecase annotation was used!. Must be fixed as well!

**Comment by de-jcup** [comment]
Another one
```
 transactionService.saveInOwnTransaction(project, newOwner,);
```
Problem: only the new owner is saved, but not the old one.

**Comment by de-jcup** [comment]
## SQL update script not necessary for getProjects() usage instead of getOwnedProjects()
Fortunately we do NOT need to migrate former data by  a database update script - reason: Inside database the 1:n relation ship between project and administrator is only kept at `ADM_PROJECT` table. And this value was correct set.

## Assumption about flaky test before and the fix of it
On the other hand this was (IMHO) the reason for the flaky tests (not 100% analysed, just an assumption):

 The former (buggy) implementation did only change the owner inside the project object but NOT  inside the related former (owner-)user object `Set` (owned projects). Depending on the hibernate caching state, the entity objects were either fetched new from database (with correct new set calculation...) or were reused with the wrong set state .

By handling this now correct the "flaky test" should now work always correct.
